# Generated by Django 2.1.4 on 2019-01-21 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('is_site', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('num_seat', models.DecimalField(decimal_places=0, max_digits=4)),
                ('dest_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Dest')),
            ],
        ),
    ]
