# Generated by Django 2.1.4 on 2019-01-21 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='facts',
            old_name='facts',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='facts',
            name='dest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Dest'),
        ),
    ]
